### ISSUE TITLE
Cannot open tty

### ISSUE THREAD

**Issue by stephane** [antono/atom-pgp#2]
After I enter my password gpg (GnuPG) 1.4.19 on Mac OS says:

> gpg: cannot open tty `/dev/tty': Device not configured

May be the option '--no-tty' could be used. I am a noob with Atom so I just tried to edit gpg.coffee to apply the change but I don't know if I must compile the coffeescript manually, etc.

**Comment by antono** [comment]
You dont need to compile this file. ~/.atom/packages/atom-pgp/lib/gpg.coffee and add --no-tty option.
I'll accept pull request/or fix myself if it works for you. Have no mac for testing.

**Comment by stephane** [comment]
I tried but w/o success. It's a bit strange that I enter the Ctrl+k p d shortcut (to decode), the plugin asks for my password twice.

**Comment by antono** [comment]
@stephane i just published new version with spawn+gpg replaced with OpenPGP.js. It should fix the issue.
