### ISSUE TITLE
'gpg' could not be spawned

### ISSUE THREAD

**Issue by Majasi** [antono/atom-pgp#3]
Thanks for this package.

I'm getting an error when trying to encrypt. After entering the passwords i get: 

```
'gpg' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```

on my mac with atom 1.4

**Comment by antono** [comment]
You need gnupg installed via homebrew or other package manager.

**Comment by olavolav** [comment]
+1

The error message says it needs to be installed and in the path and it likely is :smile: What do you think the problem is @antono, what do the package managers do that's missing?

**Comment by antono** [comment]
Its hard to deal with all available package managers... I'll take a look to
nodejs based pgp implementation soon.

**Comment by antono** [comment]
@Majasi @olavolav i just published new version with spawn+gpg replaced with OpenPGP.js. It should fix your issues.

**Comment by olavolav** [comment]
👍 Cool
